### ISSUE TITLE
Debug the heroku build failure

### ISSUE THREAD

**Issue by Jeremy-Jonas** [kowhai-2018/Final-Project#123]
Currently the heroku log states there is a build error.

**Comment by CarelS072** [comment]
```-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v1.12.3
       [1/4] Resolving packages...
       success Already up-to-date.
       Done in 1.09s.
       Running heroku-postbuild (yarn)
       yarn run v1.12.3
       $ yarn knex migrate:latest && yarn knex seed:run
       $ /tmp/build_be17e82490ccda1f4e6427acc286a8cf/node_modules/.bin/knex migrate:latest
       Using environment: production
       Batch 1 run: 4 migrations 
       /tmp/build_be17e82490ccda1f4e6427acc286a8cf/migrations/20181206104331_users.js
       /tmp/build_be17e82490ccda1f4e6427acc286a8cf/migrations/20181206104438_activities.js
       /tmp/build_be17e82490ccda1f4e6427acc286a8cf/migrations/20181206162707_dates.js
       /tmp/build_be17e82490ccda1f4e6427acc286a8cf/migrations/20181206162742_cardData.js
       $ /tmp/build_be17e82490ccda1f4e6427acc286a8cf/node_modules/.bin/knex seed:run
       Using environment: production
error: insert or update on table "cardData" violates foreign key constraint "carddata_date_id_foreign"
    at Connection.parseE (/tmp/build_be17e82490ccda1f4e6427acc286a8cf/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/tmp/build_be17e82490ccda1f4e6427acc286a8cf/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/tmp/build_be17e82490ccda1f4e6427acc286a8cf/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Build failed
```

**Comment by CarelS072** [comment]
https://github.com/tgriesser/knex/issues/637

**Comment by CarelS072** [comment]
Suspect that the seeds with dependencies are being run before the dependant rows are created causing the error

**Comment by Jeremy-Jonas** [comment]
```
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 10.x...
       Downloading and installing node 10.14.1...
       Using default npm version: 6.4.1
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.12.3)...
       Installed yarn 1.12.3
       
-----> Restoring cache
       - node_modules
       
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v1.12.3
       [1/4] Resolving packages...
       success Already up-to-date.
       Done in 1.05s.
       Running heroku-postbuild (yarn)
       yarn run v1.12.3
       $ yarn knex migrate:latest && yarn knex seed:run
       $ /tmp/build_dced74779f5f4f8b6e9b1393592c75fd/node_modules/.bin/knex migrate:latest
       Using environment: production
       Already up to date
       $ /tmp/build_dced74779f5f4f8b6e9b1393592c75fd/node_modules/.bin/knex seed:run
       Using environment: production
error: column "colour" of relation "activities" does not exist
    at Connection.parseE (/tmp/build_dced74779f5f4f8b6e9b1393592c75fd/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/tmp/build_dced74779f5f4f8b6e9b1393592c75fd/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/tmp/build_dced74779f5f4f8b6e9b1393592c75fd/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by Jeremy-Jonas** [comment]
After a database reset and redeploy we are back to the same issue, now trying to rename seed files

**Comment by Jeremy-Jonas** [comment]
Resolved by ordering the seed files with name change
